### ISSUE TITLE
request: external cc1101 support

### ISSUE THREAD

**Issue by ve6btc** [derskythe/flipperzero-subbrute#8]
since the subghz menu now supports external cc1101 boards (and quite well thanks) respectfully id ask that this application does as well for hse and testing with external resonant antennas on a given frequency

thanks

**Comment by xMasterX** [comment]
Yes it works with external module on unleashed firmware

why you opened whole issue if you can just try to use it, set module to external and then open this app?

**Comment by ve6btc** [comment]
My most sincere apologies I had assumed that just the sub ghz section of the flipper was updated to allow internal and external cc1101 I did not know that when flipping it in the sub ghz portion this would effect associated apps such as the brute force my apologies I assumed when tuning the brute force it was just using internal and had no way of knowing that I know of isolating which module the app was using 

thank you for this and apologies for wasting your time on this “issue”

**Comment by tomasvanagas** [comment]
Thank you for asking this. In the SubGhz bruteforce app it is not clear that you're using external antenna. Perhaps it would be a good idea to indicate which antenna is currently in use?
