### ISSUE TITLE
Adding support for new protocol

### ISSUE THREAD

**Issue by dan3333** [derskythe/flipperzero-subbrute#9]
I am trying to add support for a new protocol used by my garage gate.
Flipper identifies the code as: Phoenix_V2 52bit 433.92AM
I dont know anything about the protocol other than that.
I am duplicating an existing SubBruteProtocol struct and updating the different files but I dont understand the meaning of "te" and of "repeat" fields in the struct.

**Comment by xMasterX** [comment]
Bruteforcing 24bit static code will take about 800 hours

Can you imagine how much time will take 52bit?

This is waste of time, it will not work
